name: task_config

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    pcds:
      shape: [6]
      type: pcd
    qpos:
      shape: [9]
      type: low_dim
  action:
    shape: [9]
  goal:
    task_emb:
      shape: [512]

env_runner:
  _target_: diffusion_policy.env_runner.pusht_image_runner.PushTImageRunner
  n_train: 6
  n_train_vis: 2
  train_start_seed: 0
  n_test: 50
  n_test_vis: 4
  legacy_test: True
  test_start_seed: 100000
  max_steps: 300
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  fps: 10
  past_action: ${past_action_visible}
  n_envs: null

dataset:
  _target_: diffusion_policy.dataset.robot_spUnet_dataset.RobotPointCloudDataset
  zarr_path: diffusion_policy/data/useless.zarr
  horizon: ${horizon}
  n_obs_steps: ${n_obs_steps}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.02
  batch_size: 32
  max_train_episodes: null
  task_name: ${task.name}
  transform_pcd:
    - _target_: roboverse_learn.algorithms.utils.transformpcd.GridSamplePCD
      grid_size: 0.005
      hash_type: fnv
      mode: train
      return_grid_coord: true
      return_displacement: false
      keys:
        - coord
        - color
    - _target_: roboverse_learn.algorithms.utils.transformpcd.NormalizeColorPCD
    - _target_: roboverse_learn.algorithms.utils.transformpcd.ShufflePointPCD
    - _target_: roboverse_learn.algorithms.utils.transformpcd.ToTensorPCD
    - _target_: roboverse_learn.algorithms.utils.transformpcd.CollectPCD
      keys:
        - coord
        - grid_coord
      feat_keys:
        - color
        - coord
