defaults:
  - _self_

encoder_name: RGB_ResNet18

name: robot_${task.name}
_target_: diffusion_policy.workspace.robotworkspace.RobotWorkspace

task_name: ${task.name}
shape_meta: ${task.shape_meta}
exp_name: "default"

policy:
  'lr': args['lr'],
  'num_queries': args['chunk_size'],
  'kl_weight': args['kl_weight'],
  'hidden_dim': args['hidden_dim'],
  'dim_feedforward': args['dim_feedforward'],
  'lr_backbone': lr_backbone,
  'backbone': backbone,
  'enc_layers': enc_layers,
  'dec_layers': dec_layers,
  'nheads': nheads,
  'camera_names': camera_names,
  'state_dim': args['state_dim']


logging:
  project: RoboVerse_DP
  resume: True
  mode: online
  name: ${now:%Y.%m.%d-%H.%M.%S}_${encoder_name}_${task_name}
  tags: ${now:%Y.%m.%d-%H.%M.%S}_${encoder_name}_${task_name}
  id: null
  group: null

checkpoint:
  topk:
    monitor_key: test_mean_score
    mode: max
    k: 5
    format_str: 'epoch={epoch:04d}-test_mean_score={test_mean_score:.3f}.ckpt'
  save_last_ckpt: True
  save_last_snapshot: False
  save_root_dir: info/outputs/DP/${now:%Y.%m.%d}/${now:%H.%M.%S}_${encoder_name}_${task_name}

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: info/outputs/DP/${now:%Y.%m.%d}/${now:%H.%M.%S}_${encoder_name}_${task_name}
  sweep:
    dir: info/outputs/DP/${now:%Y.%m.%d}/${now:%H.%M.%S}_${encoder_name}_${task_name}
    subdir: ${hydra.job.num}
