defaults:
  - _self_
  - task: default_task_resnet_spUnet_mutual_attention

encoder_name: Fusion_ResNet18_spUnet_Mutual_Attention

name: robot_${task.name}
_target_: mlp_policy.workspace.robotworkspace.RobotWorkspace

task_name: ${task.name}
shape_meta: ${task.shape_meta}
exp_name: "default"

horizon: 8
n_obs_steps: 3
n_action_steps: 4
n_latency_steps: 0
dataset_obs_steps: ${n_obs_steps}
past_action_visible: False
keypoint_visible_rate: 1.0
obs_as_global_cond: True

policy_runner:
  action:
    action_type: "ee"
    ee_cfg:
      rotation_rep: "quaternion"
      gripper_rep: "q_pos"
    delta: False
  obs:
    obs_type: "ee"
    ee_cfg:
      rotation_rep: "quaternion"
      gripper_rep: "q_pos"
policy:
  _target_: mlp_policy.policy.multimodal_policy.MultiModalPolicy

  shape_meta: ${shape_meta}

  noise_scheduler:
    _target_: diffusers.schedulers.scheduling_ddpm.DDPMScheduler
    beta_end: 0.02
    beta_schedule: squaredcos_cap_v2
    beta_start: 0.0001
    clip_sample: true
    num_train_timesteps: 100
    prediction_type: epsilon
    variance_type: fixed_small

  obs_encoder:
    _target_: mlp_policy.model.vision.multimodal_encoder.MultiModalEncoder
    shape_meta: ${shape_meta}
    img_model:
      _target_: mlp_policy.model.vision.model_getter.get_resnet
      name: resnet18
      weights: null
    pntcloud_model:
      _target_: mlp_policy.model.vision.model_getter.get_spUnet_encoder
      shape: ${shape_meta.obs.point_cloud.shape}
      pcd_model:
        _target_: mlp_policy.model.vision.model_getter.get_spUnet
        in_channels: 3
        num_classes: 0
        pretrained_path: null
      n_obs_steps: ${n_obs_steps}
      pcd_nsample: 16
      pcd_npoints: 2048
      use_mask: false
      bg_ratio: 0.0
      pcd_hidden_dim: 96
      projector_layers: 2
      projector_channels: ${task.shape_meta.obs.point_cloud.projector_channels}

    robot_state_model:
      _target_: mlp_policy.model.vision.model_getter.get_state_mlp
      observation_space: ${shape_meta.obs}

    img_encoder_args:
      resize_shape: null
      crop_shape: null
      random_crop: True
      use_group_norm: True
      imagenet_norm: True

    fusion_args:
      fusion_method: cross_attention
      embed_dim: 256
      num_heads: 8
      img_dim: 512
      pc_dim: 128
      state_dim: 64
      mutual_attention: True

  horizon: ${horizon}
  n_action_steps: ${eval:'${n_action_steps}+${n_latency_steps}'}
  n_obs_steps: ${n_obs_steps}
  num_inference_steps: 100
  obs_as_global_cond: ${obs_as_global_cond}
  # crop_shape: null
  diffusion_step_embed_dim: 128
  down_dims: [512, 1024, 2048]
  #down_dims: [256, 512, 1024]
  kernel_size: 5
  n_groups: 8
  cond_predict_scale: True

  # scheduler.step params
  # predict_epsilon: True


dataloader:
  batch_size: 32
  num_workers: 0
  shuffle: True
  pin_memory: True
  persistent_workers: False

val_dataloader:
  batch_size: 32
  num_workers: 0
  shuffle: False
  pin_memory: True
  persistent_workers: False

optimizer:
  _target_: torch.optim.AdamW
  lr: 5.0e-5
  betas: [0.95, 0.999]
  eps: 1.0e-8
  weight_decay: 1.0e-6

training:
  device: "cuda:0"
  seed: 42
  debug: False
  resume: True
  tag: 0
  output_dir: ""
  # optimization
  lr_scheduler: cosine
  lr_warmup_steps: 500
  num_epochs: 1000
  gradient_accumulate_every: 1
  # EMA destroys performance when used with BatchNorm
  # replace BatchNorm with GroupNorm.
  use_ema: False
  freeze_encoder: False
  # training loop control
  # in epochs
  rollout_every: 50
  checkpoint_every: 1000
  val_every: 5
  sample_every: 5
  # steps per epoch
  max_train_steps: 250
  max_val_steps: 250
  # misc
  tqdm_interval_sec: 1.0

logging:
  project: RoboVerse_DP
  resume: True
  mode: online
  name: ${now:%Y.%m.%d-%H.%M.%S}_${encoder_name}_${task_name}
  tags: ${now:%Y.%m.%d-%H.%M.%S}_${encoder_name}_${task_name}
  id: null
  group: null

checkpoint:
  topk:
    monitor_key: test_mean_score
    mode: max
    k: 5
    format_str: 'epoch={epoch:04d}-test_mean_score={test_mean_score:.3f}.ckpt'
  save_last_ckpt: True
  save_last_snapshot: False
  save_root_dir: info/outputs/DP/${now:%Y.%m.%d}/${now:%H.%M.%S}_${encoder_name}_${task_name}

multi_run:
  run_dir: info/outputs/DP/${now:%Y.%m.%d}/${now:%H.%M.%S}_${encoder_name}_${task_name}
  wandb_name_base: ${now:%Y.%m.%d-%H.%M.%S}_${encoder_name}_${task_name}

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: info/outputs/DP/${now:%Y.%m.%d}/${now:%H.%M.%S}_${encoder_name}_${task_name}
  sweep:
    dir: info/outputs/DP/${now:%Y.%m.%d}/${now:%H.%M.%S}_${encoder_name}_${task_name}
    subdir: ${hydra.job.num}
